### ISSUE TITLE
Cannot find module 'vue-router/auto' or its corresponding type declarations

### ISSUE THREAD

**Issue by Ribeiro-Tiago** [posva/unplugin-vue-router#323]
With version 0.8.x the typings for vue-router/auto disappeared. They don't seem to be part of the `unplugin-vue-router/client` that gets added to tsconfig, nor are they present in the typed-router.d.ts anymore 

![Screenshot 2024-02-22 at 16 04 53](https://github.com/posva/unplugin-vue-router/assets/11082362/3eaeefce-a19e-4b87-9b70-d0b1464d2e60)

which leands to 

![Screenshot 2024-02-22 at 16 04 11](https://github.com/posva/unplugin-vue-router/assets/11082362/48f53853-6443-4029-81f6-9c1b408f04c8)

repo: https://github.com/Ribeiro-Tiago/repro-repo

**Comment by posva** [comment]
I cannot reproduce, I get the same issue as #322. You might have hit a cache issue?

**Comment by Ribeiro-Tiago** [comment]
:( 

what would be caching this do you think ? I created a new project for that reproducible

**Comment by posva** [comment]
That’s weird but I can’t reproduce it

**Comment by posva** [comment]
Can you try with the new version? I still can't reproduce it

**Comment by juw177** [comment]
I can reproduce it. typed-router.d.ts not having the module after upgrading to 0.8

**Comment by posva** [comment]
@juw177 there is a client file to add (instructions in changelog)

BTW, don’t open an issue on vuetify about it, it has nothing to do with it 😅

**Comment by juw177** [comment]
Thanks @posva , yes, I have added `"types": ["unplugin-vue-router/client"],` to tsconfig but still didn't work.

**Comment by Ribeiro-Tiago** [comment]
Still nothing with 0.8.4. Not sure if it matters, but I'm using yarn v4 pnp as package manager

**Comment by lfhenrl** [comment]
I have the same problem have to go back to 7.0.

**Comment by posva** [comment]
@Ribeiro-Tiago https://github.com/posva/unplugin-vue-router/issues/118
@juw177 the module declaration was moved to unplugin-vue-router/client, that's why it's not there.
I will be happy to take a look if anybody can provide a reproduction (without yarn pnp ofc)

**Comment by posva** [comment]
Setting `moduleResolution: Bundler` (+ changes mentioned in changelog) fix it for the vuetify template. I added that to the docs: 76f9392

**Comment by juw177** [comment]
Thanks @posva , that worked. As for @Ribeiro-Tiago , I think the problem with your confis is you have defined types twice so overwrote the other.

**Comment by lfhenrl** [comment]
Thanks It was the "moduleResolution": "Bundler" that fix it.

**Comment by Ribeiro-Tiago** [comment]
@posva indeed, using `"moduleResolution": "Bundler",` does the trick

It does break typing for vuex imports, `Could not find a declaration file for module 'vuex'. but this result could not be resolved when respecting package.json "exports". The 'vuex' library may need to update its package.json or typings`, but [this](https://stackoverflow.com/a/76478851) seems to be a good enough workaround, and I'll be replacing vuex with pina soon ™️  so doesn't matter much :p

**Comment by posva** [comment]
I think Vuex types need to be fixed 😅

**Comment by plasmatech8** [comment]
None of the the discussions seem to solve the typescript error for me, but a good old `// @ts-ignore` does the trick for me.

<details>
<summary>
On latest Vuetify app with routing + typescript.
</summary>

```
# npm create vuetify@latest

Need to install the following packages:
create-vuetify@2.2.0
Ok to proceed? (y) 

Vuetify.js - Material Component Framework for Vue

✔ Project name: … vuetify-project
✔ The project path: XYZ
✔ Which preset would you like to install? › Base (Default, Routing)
✔ Use TypeScript? … Yes
✔ Would you like to install dependencies with yarn, npm, pnpm, or bun? › npm
```

Comes with `"unplugin-vue-router": "^0.8.4",`

</details>

**Comment by vzakharov** [comment]
> For folks who ran into this even _with_ `moduleResolution: Bundler` — try bumping up `vue-router` from 4.1 to 4.3. That fixed it for me!

This (and none of the previous solutions in this page) was what made it work for me, thank you!
